# Fabric Loom
loom_version=1.17.19

# Minecraft / Fabric versions
minecraft_version=1.21.11
loader_version=0.19.3
fabric_version=0.141.6+1.21.11
yarn_mappings=1.21.11+build.6

# Mod Properties
mod_version=2.2.0
maven_group=com.findspnr
archives_base_name=findspnr

# Java
java_version=21
org.gradle.jvmargs=-Xmx2G
